#pragma once
typedef struct ccn_node ccn_node;
struct ccn_node *ACGids(struct ccn_node *node);
struct ccn_node *ACGarrexpr(struct ccn_node *node);
struct ccn_node *ACGfundefs(struct ccn_node *node);
struct ccn_node *ACGstefun(struct ccn_node *node);
struct ccn_node *ACGstevar(struct ccn_node *node);
struct ccn_node *ACGbool(struct ccn_node *node);
struct ccn_node *ACGfloat(struct ccn_node *node);
struct ccn_node *ACGnum(struct ccn_node *node);
struct ccn_node *ACGvar(struct ccn_node *node);
struct ccn_node *ACGexprs(struct ccn_node *node);
struct ccn_node *ACGfuncall(struct ccn_node *node);
struct ccn_node *ACGcast(struct ccn_node *node);
struct ccn_node *ACGvarlet(struct ccn_node *node);
struct ccn_node *ACGternaryop(struct ccn_node *node);
struct ccn_node *ACGmonop(struct ccn_node *node);
struct ccn_node *ACGbinop(struct ccn_node *node);
struct ccn_node *ACGreturn(struct ccn_node *node);
struct ccn_node *ACGfor(struct ccn_node *node);
struct ccn_node *ACGdowhile(struct ccn_node *node);
struct ccn_node *ACGwhile(struct ccn_node *node);
struct ccn_node *ACGifelse(struct ccn_node *node);
struct ccn_node *ACGexprstmt(struct ccn_node *node);
struct ccn_node *ACGassign(struct ccn_node *node);
struct ccn_node *ACGstmts(struct ccn_node *node);
struct ccn_node *ACGvardecl(struct ccn_node *node);
struct ccn_node *ACGparam(struct ccn_node *node);
struct ccn_node *ACGfunbody(struct ccn_node *node);
struct ccn_node *ACGfundef(struct ccn_node *node);
struct ccn_node *ACGglobdef(struct ccn_node *node);
struct ccn_node *ACGglobdecl(struct ccn_node *node);
struct ccn_node *ACGdecls(struct ccn_node *node);
struct ccn_node *ACGprogram(struct ccn_node *node);
ccn_node *CBCEcast(ccn_node *);
ccn_node *CBCEcast(ccn_node *);
ccn_node *CBCEbinop(ccn_node *);
ccn_node *CBCEbinop(ccn_node *);
ccn_node *CBCEbool(ccn_node *);
ccn_node *CBCEbool(ccn_node *);
ccn_node *CBCEmonop(ccn_node *);
ccn_node *CBCEmonop(ccn_node *);
ccn_node *CBCEfuncall(ccn_node *);
ccn_node *CBCEfuncall(ccn_node *);
ccn_node *CBCEfloat(ccn_node *);
ccn_node *CBCEfloat(ccn_node *);
ccn_node *CBCEternaryop(ccn_node *);
ccn_node *CBCEternaryop(ccn_node *);
ccn_node *CBCEnum(ccn_node *);
ccn_node *CBCEnum(ccn_node *);
ccn_node *CBCEvar(ccn_node *);
ccn_node *CBCEvar(ccn_node *);
ccn_node *CBDCbinop(ccn_node *);
ccn_node *CBDCbinop(ccn_node *);
ccn_node *AUCEcast(ccn_node *);
ccn_node *AUCEcast(ccn_node *);
ccn_node *AUCEbinop(ccn_node *);
ccn_node *AUCEbinop(ccn_node *);
ccn_node *AUCEbool(ccn_node *);
ccn_node *AUCEbool(ccn_node *);
ccn_node *AUCEmonop(ccn_node *);
ccn_node *AUCEmonop(ccn_node *);
ccn_node *AUCEfuncall(ccn_node *);
ccn_node *AUCEfuncall(ccn_node *);
ccn_node *AUCEfloat(ccn_node *);
ccn_node *AUCEfloat(ccn_node *);
ccn_node *AUCEvar(ccn_node *);
ccn_node *AUCEvar(ccn_node *);
ccn_node *AUCEnum(ccn_node *);
ccn_node *AUCEnum(ccn_node *);
ccn_node *TMAFfundef(ccn_node *);
ccn_node *TMAFfundef(ccn_node *);
ccn_node *TMAFfunbody(ccn_node *);
ccn_node *TMAFfunbody(ccn_node *);
ccn_node *TMAFassign(ccn_node *);
ccn_node *TMAFassign(ccn_node *);
ccn_node *TMAFdowhile(ccn_node *);
ccn_node *TMAFdowhile(ccn_node *);
ccn_node *TMAFcast(ccn_node *);
ccn_node *TMAFcast(ccn_node *);
ccn_node *TMAFbinop(ccn_node *);
ccn_node *TMAFbinop(ccn_node *);
ccn_node *TMAFbool(ccn_node *);
ccn_node *TMAFbool(ccn_node *);
ccn_node *TMAFfor(ccn_node *);
ccn_node *TMAFfor(ccn_node *);
ccn_node *TMAFexprs(ccn_node *);
ccn_node *TMAFexprs(ccn_node *);
ccn_node *TMAFfloat(ccn_node *);
ccn_node *TMAFfloat(ccn_node *);
ccn_node *TMAFfuncall(ccn_node *);
ccn_node *TMAFfuncall(ccn_node *);
ccn_node *TMAFifelse(ccn_node *);
ccn_node *TMAFifelse(ccn_node *);
ccn_node *TMAFwhile(ccn_node *);
ccn_node *TMAFwhile(ccn_node *);
ccn_node *TMAFreturn(ccn_node *);
ccn_node *TMAFreturn(ccn_node *);
ccn_node *TMAFmonop(ccn_node *);
ccn_node *TMAFmonop(ccn_node *);
ccn_node *TMAFnum(ccn_node *);
ccn_node *TMAFnum(ccn_node *);
ccn_node *TMAFvar(ccn_node *);
ccn_node *TMAFvar(ccn_node *);
ccn_node *CFTWfor(ccn_node *);
ccn_node *CFTWfor(ccn_node *);
ccn_node *RAprogram(ccn_node *);
ccn_node *RAprogram(ccn_node *);
ccn_node *RAdecls(ccn_node *);
ccn_node *RAdecls(ccn_node *);
ccn_node *RAglobdef(ccn_node *);
ccn_node *RAglobdef(ccn_node *);
ccn_node *RAfunbody(ccn_node *);
ccn_node *RAfunbody(ccn_node *);
ccn_node *RAvardecl(ccn_node *);
ccn_node *RAvardecl(ccn_node *);
ccn_node *LFTSFprogram(ccn_node *);
ccn_node *LFTSFprogram(ccn_node *);
ccn_node *LFTSFfuncall(ccn_node *);
ccn_node *LFTSFfuncall(ccn_node *);
ccn_node *CFSprogram(ccn_node *);
ccn_node *CFSprogram(ccn_node *);
ccn_node *CFSfundef(ccn_node *);
ccn_node *CFSfundef(ccn_node *);
ccn_node *CFSparam(ccn_node *);
ccn_node *CFSparam(ccn_node *);
ccn_node *CVSprogram(ccn_node *);
ccn_node *CVSprogram(ccn_node *);
ccn_node *CVSfundef(ccn_node *);
ccn_node *CVSfundef(ccn_node *);
ccn_node *CVSfunbody(ccn_node *);
ccn_node *CVSfunbody(ccn_node *);
ccn_node *CVSfuncall(ccn_node *);
ccn_node *CVSfuncall(ccn_node *);
ccn_node *CVSglobdecl(ccn_node *);
ccn_node *CVSglobdecl(ccn_node *);
ccn_node *CVSglobdef(ccn_node *);
ccn_node *CVSglobdef(ccn_node *);
ccn_node *CVSparam(ccn_node *);
ccn_node *CVSparam(ccn_node *);
ccn_node *CVSvardecl(ccn_node *);
ccn_node *CVSvardecl(ccn_node *);
ccn_node *CVSvar(ccn_node *);
ccn_node *CVSvar(ccn_node *);
ccn_node *CVSvarlet(ccn_node *);
ccn_node *CVSvarlet(ccn_node *);
ccn_node *RFIfunbody(ccn_node *);
ccn_node *RFIfunbody(ccn_node *);
ccn_node *RFIfor(ccn_node *);
ccn_node *RFIfor(ccn_node *);
ccn_node *RFIassign(ccn_node *);
ccn_node *RFIassign(ccn_node *);
ccn_node *RFIvardecl(ccn_node *);
ccn_node *RFIvardecl(ccn_node *);
ccn_node *RFIstmts(ccn_node *);
ccn_node *RFIstmts(ccn_node *);
ccn_node *RFIfuncall(ccn_node *);
ccn_node *RFIfuncall(ccn_node *);
ccn_node *RFIvar(ccn_node *);
ccn_node *RFIvar(ccn_node *);
ccn_node *RFIvarlet(ccn_node *);
ccn_node *RFIvarlet(ccn_node *);
struct ccn_node *PRTids(struct ccn_node *node);
struct ccn_node *PRTarrexpr(struct ccn_node *node);
struct ccn_node *PRTfundefs(struct ccn_node *node);
struct ccn_node *PRTstefun(struct ccn_node *node);
struct ccn_node *PRTstevar(struct ccn_node *node);
struct ccn_node *PRTbool(struct ccn_node *node);
struct ccn_node *PRTfloat(struct ccn_node *node);
struct ccn_node *PRTnum(struct ccn_node *node);
struct ccn_node *PRTvar(struct ccn_node *node);
struct ccn_node *PRTexprs(struct ccn_node *node);
struct ccn_node *PRTfuncall(struct ccn_node *node);
struct ccn_node *PRTcast(struct ccn_node *node);
struct ccn_node *PRTvarlet(struct ccn_node *node);
struct ccn_node *PRTternaryop(struct ccn_node *node);
struct ccn_node *PRTmonop(struct ccn_node *node);
struct ccn_node *PRTbinop(struct ccn_node *node);
struct ccn_node *PRTreturn(struct ccn_node *node);
struct ccn_node *PRTfor(struct ccn_node *node);
struct ccn_node *PRTdowhile(struct ccn_node *node);
struct ccn_node *PRTwhile(struct ccn_node *node);
struct ccn_node *PRTifelse(struct ccn_node *node);
struct ccn_node *PRTexprstmt(struct ccn_node *node);
struct ccn_node *PRTassign(struct ccn_node *node);
struct ccn_node *PRTstmts(struct ccn_node *node);
struct ccn_node *PRTvardecl(struct ccn_node *node);
struct ccn_node *PRTparam(struct ccn_node *node);
struct ccn_node *PRTfunbody(struct ccn_node *node);
struct ccn_node *PRTfundef(struct ccn_node *node);
struct ccn_node *PRTglobdef(struct ccn_node *node);
struct ccn_node *PRTglobdecl(struct ccn_node *node);
struct ccn_node *PRTdecls(struct ccn_node *node);
struct ccn_node *PRTprogram(struct ccn_node *node);
ccn_node *SPdoScanParse(ccn_node *);
ccn_node *CPYids(ccn_node *);
ccn_node *DELids(ccn_node *);
ccn_node *CHKids(ccn_node *);
ccn_node *CPYarrexpr(ccn_node *);
ccn_node *DELarrexpr(ccn_node *);
ccn_node *CHKarrexpr(ccn_node *);
ccn_node *CPYfundefs(ccn_node *);
ccn_node *DELfundefs(ccn_node *);
ccn_node *CHKfundefs(ccn_node *);
ccn_node *CPYstefun(ccn_node *);
ccn_node *DELstefun(ccn_node *);
ccn_node *CHKstefun(ccn_node *);
ccn_node *CPYstevar(ccn_node *);
ccn_node *DELstevar(ccn_node *);
ccn_node *CHKstevar(ccn_node *);
ccn_node *CPYbool(ccn_node *);
ccn_node *DELbool(ccn_node *);
ccn_node *CHKbool(ccn_node *);
ccn_node *CPYfloat(ccn_node *);
ccn_node *DELfloat(ccn_node *);
ccn_node *CHKfloat(ccn_node *);
ccn_node *CPYnum(ccn_node *);
ccn_node *DELnum(ccn_node *);
ccn_node *CHKnum(ccn_node *);
ccn_node *CPYvar(ccn_node *);
ccn_node *DELvar(ccn_node *);
ccn_node *CHKvar(ccn_node *);
ccn_node *CPYexprs(ccn_node *);
ccn_node *DELexprs(ccn_node *);
ccn_node *CHKexprs(ccn_node *);
ccn_node *CPYfuncall(ccn_node *);
ccn_node *DELfuncall(ccn_node *);
ccn_node *CHKfuncall(ccn_node *);
ccn_node *CPYcast(ccn_node *);
ccn_node *DELcast(ccn_node *);
ccn_node *CHKcast(ccn_node *);
ccn_node *CPYvarlet(ccn_node *);
ccn_node *DELvarlet(ccn_node *);
ccn_node *CHKvarlet(ccn_node *);
ccn_node *CPYternaryop(ccn_node *);
ccn_node *DELternaryop(ccn_node *);
ccn_node *CHKternaryop(ccn_node *);
ccn_node *CPYmonop(ccn_node *);
ccn_node *DELmonop(ccn_node *);
ccn_node *CHKmonop(ccn_node *);
ccn_node *CPYbinop(ccn_node *);
ccn_node *DELbinop(ccn_node *);
ccn_node *CHKbinop(ccn_node *);
ccn_node *CPYreturn(ccn_node *);
ccn_node *DELreturn(ccn_node *);
ccn_node *CHKreturn(ccn_node *);
ccn_node *CPYfor(ccn_node *);
ccn_node *DELfor(ccn_node *);
ccn_node *CHKfor(ccn_node *);
ccn_node *CPYdowhile(ccn_node *);
ccn_node *DELdowhile(ccn_node *);
ccn_node *CHKdowhile(ccn_node *);
ccn_node *CPYwhile(ccn_node *);
ccn_node *DELwhile(ccn_node *);
ccn_node *CHKwhile(ccn_node *);
ccn_node *CPYifelse(ccn_node *);
ccn_node *DELifelse(ccn_node *);
ccn_node *CHKifelse(ccn_node *);
ccn_node *CPYexprstmt(ccn_node *);
ccn_node *DELexprstmt(ccn_node *);
ccn_node *CHKexprstmt(ccn_node *);
ccn_node *CPYassign(ccn_node *);
ccn_node *DELassign(ccn_node *);
ccn_node *CHKassign(ccn_node *);
ccn_node *CPYstmts(ccn_node *);
ccn_node *DELstmts(ccn_node *);
ccn_node *CHKstmts(ccn_node *);
ccn_node *CPYvardecl(ccn_node *);
ccn_node *DELvardecl(ccn_node *);
ccn_node *CHKvardecl(ccn_node *);
ccn_node *CPYparam(ccn_node *);
ccn_node *DELparam(ccn_node *);
ccn_node *CHKparam(ccn_node *);
ccn_node *CPYfunbody(ccn_node *);
ccn_node *DELfunbody(ccn_node *);
ccn_node *CHKfunbody(ccn_node *);
ccn_node *CPYfundef(ccn_node *);
ccn_node *DELfundef(ccn_node *);
ccn_node *CHKfundef(ccn_node *);
ccn_node *CPYglobdef(ccn_node *);
ccn_node *DELglobdef(ccn_node *);
ccn_node *CHKglobdef(ccn_node *);
ccn_node *CPYglobdecl(ccn_node *);
ccn_node *DELglobdecl(ccn_node *);
ccn_node *CHKglobdecl(ccn_node *);
ccn_node *CPYdecls(ccn_node *);
ccn_node *DELdecls(ccn_node *);
ccn_node *CHKdecls(ccn_node *);
ccn_node *CPYprogram(ccn_node *);
ccn_node *DELprogram(ccn_node *);
ccn_node *CHKprogram(ccn_node *);
