#include "ccngen/actions.h"
#include "ccn/ccn_types.h"
#include "ccn/dynamic_core.h"
const ccn_trav_ft assemblycodegeneration_vtable[_NT_SIZE] = { &TRAVerror, &ACGids, &ACGarrexpr, &ACGfundefs, &ACGstefun, &ACGstevar, &ACGbool, &ACGfloat, &ACGnum, &ACGvar, &ACGexprs, &ACGfuncall, &ACGcast, &ACGvarlet, &ACGternaryop, &ACGmonop, &ACGbinop, &ACGreturn, &ACGfor, &ACGdowhile, &ACGwhile, &ACGifelse, &ACGexprstmt, &ACGassign, &ACGstmts, &ACGvardecl, &ACGparam, &ACGfunbody, &ACGfundef, &ACGglobdef, &ACGglobdecl, &ACGdecls, &ACGprogram, };
const ccn_trav_ft compilingbooleancastexpressions_vtable[_NT_SIZE] = { &TRAVerror, &TRAVnop, &TRAVchildren, &TRAVchildren, &TRAVnop, &TRAVnop, &CBCEbool, &CBCEfloat, &CBCEnum, &CBCEvar, &TRAVchildren, &CBCEfuncall, &CBCEcast, &TRAVchildren, &CBCEternaryop, &CBCEmonop, &CBCEbinop, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVnop, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVnop, &TRAVchildren, &TRAVchildren, };
const ccn_trav_ft compilingbooleandisjunctionandconjunction_vtable[_NT_SIZE] = { &TRAVerror, &TRAVnop, &TRAVchildren, &TRAVchildren, &TRAVnop, &TRAVnop, &TRAVnop, &TRAVnop, &TRAVnop, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVchildren, &CBDCbinop, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVnop, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVnop, &TRAVchildren, &TRAVchildren, };
const ccn_trav_ft annotateuselesscastexpressions_vtable[_NT_SIZE] = { &TRAVerror, &TRAVnop, &TRAVchildren, &TRAVchildren, &TRAVnop, &TRAVnop, &AUCEbool, &AUCEfloat, &AUCEnum, &AUCEvar, &TRAVchildren, &AUCEfuncall, &AUCEcast, &TRAVchildren, &TRAVchildren, &AUCEmonop, &AUCEbinop, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVnop, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVnop, &TRAVchildren, &TRAVchildren, };
const ccn_trav_ft typematchingassignmentsfuncalls_vtable[_NT_SIZE] = { &TRAVerror, &TRAVnop, &TRAVchildren, &TRAVchildren, &TRAVnop, &TRAVnop, &TMAFbool, &TMAFfloat, &TMAFnum, &TMAFvar, &TMAFexprs, &TMAFfuncall, &TMAFcast, &TRAVchildren, &TRAVchildren, &TMAFmonop, &TMAFbinop, &TMAFreturn, &TMAFfor, &TMAFdowhile, &TMAFwhile, &TMAFifelse, &TRAVchildren, &TMAFassign, &TRAVchildren, &TRAVchildren, &TRAVnop, &TMAFfunbody, &TMAFfundef, &TRAVchildren, &TRAVnop, &TRAVchildren, &TRAVchildren, };
const ccn_trav_ft convertfortowhile_vtable[_NT_SIZE] = { &TRAVerror, &TRAVnop, &TRAVchildren, &TRAVchildren, &TRAVnop, &TRAVnop, &TRAVnop, &TRAVnop, &TRAVnop, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVchildren, &CFTWfor, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVnop, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVnop, &TRAVchildren, &TRAVchildren, };
const ccn_trav_ft regularassignments_vtable[_NT_SIZE] = { &TRAVerror, &TRAVnop, &TRAVchildren, &TRAVchildren, &TRAVnop, &TRAVnop, &TRAVnop, &TRAVnop, &TRAVnop, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVchildren, &RAvardecl, &TRAVnop, &RAfunbody, &TRAVchildren, &RAglobdef, &TRAVnop, &RAdecls, &RAprogram, };
const ccn_trav_ft linkfuncallstostefunnode_vtable[_NT_SIZE] = { &TRAVerror, &TRAVnop, &TRAVchildren, &TRAVchildren, &TRAVnop, &TRAVnop, &TRAVnop, &TRAVnop, &TRAVnop, &TRAVchildren, &TRAVchildren, &LFTSFfuncall, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVnop, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVnop, &TRAVchildren, &LFTSFprogram, };
const ccn_trav_ft createfunctionsymboltableentries_vtable[_NT_SIZE] = { &TRAVerror, &TRAVnop, &TRAVchildren, &TRAVchildren, &TRAVnop, &TRAVnop, &TRAVnop, &TRAVnop, &TRAVnop, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVchildren, &CFSparam, &TRAVchildren, &CFSfundef, &TRAVchildren, &TRAVnop, &TRAVchildren, &CFSprogram, };
const ccn_trav_ft createvariablesymboltableentries_vtable[_NT_SIZE] = { &TRAVerror, &TRAVnop, &TRAVchildren, &TRAVchildren, &TRAVnop, &TRAVnop, &TRAVnop, &TRAVnop, &TRAVnop, &CVSvar, &TRAVchildren, &CVSfuncall, &TRAVchildren, &CVSvarlet, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVchildren, &CVSvardecl, &CVSparam, &CVSfunbody, &CVSfundef, &CVSglobdef, &CVSglobdecl, &TRAVchildren, &CVSprogram, };
const ccn_trav_ft renameforidentifiers_vtable[_NT_SIZE] = { &TRAVerror, &TRAVnop, &TRAVchildren, &TRAVchildren, &TRAVnop, &TRAVnop, &TRAVnop, &TRAVnop, &TRAVnop, &RFIvar, &TRAVchildren, &RFIfuncall, &TRAVchildren, &RFIvarlet, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVchildren, &RFIfor, &TRAVchildren, &TRAVchildren, &TRAVchildren, &TRAVchildren, &RFIassign, &RFIstmts, &RFIvardecl, &TRAVnop, &RFIfunbody, &TRAVchildren, &TRAVchildren, &TRAVnop, &TRAVchildren, &TRAVchildren, };
const ccn_trav_ft print_vtable[_NT_SIZE] = { &TRAVerror, &PRTids, &PRTarrexpr, &PRTfundefs, &PRTstefun, &PRTstevar, &PRTbool, &PRTfloat, &PRTnum, &PRTvar, &PRTexprs, &PRTfuncall, &PRTcast, &PRTvarlet, &PRTternaryop, &PRTmonop, &PRTbinop, &PRTreturn, &PRTfor, &PRTdowhile, &PRTwhile, &PRTifelse, &PRTexprstmt, &PRTassign, &PRTstmts, &PRTvardecl, &PRTparam, &PRTfunbody, &PRTfundef, &PRTglobdef, &PRTglobdecl, &PRTdecls, &PRTprogram, };
const ccn_pass_ft ccn_pass_vtable[_PASS_SIZE] = { &PASSerror, &SPdoScanParse, };
const ccn_trav_ft ccn_copy_vtable[_NT_SIZE] = { &TRAVerror, &CPYids, &CPYarrexpr, &CPYfundefs, &CPYstefun, &CPYstevar, &CPYbool, &CPYfloat, &CPYnum, &CPYvar, &CPYexprs, &CPYfuncall, &CPYcast, &CPYvarlet, &CPYternaryop, &CPYmonop, &CPYbinop, &CPYreturn, &CPYfor, &CPYdowhile, &CPYwhile, &CPYifelse, &CPYexprstmt, &CPYassign, &CPYstmts, &CPYvardecl, &CPYparam, &CPYfunbody, &CPYfundef, &CPYglobdef, &CPYglobdecl, &CPYdecls, &CPYprogram, };
const ccn_trav_ft ccn_check_vtable[_NT_SIZE] = { &TRAVerror, &CHKids, &CHKarrexpr, &CHKfundefs, &CHKstefun, &CHKstevar, &CHKbool, &CHKfloat, &CHKnum, &CHKvar, &CHKexprs, &CHKfuncall, &CHKcast, &CHKvarlet, &CHKternaryop, &CHKmonop, &CHKbinop, &CHKreturn, &CHKfor, &CHKdowhile, &CHKwhile, &CHKifelse, &CHKexprstmt, &CHKassign, &CHKstmts, &CHKvardecl, &CHKparam, &CHKfunbody, &CHKfundef, &CHKglobdef, &CHKglobdecl, &CHKdecls, &CHKprogram, };
const ccn_trav_ft ccn_free_vtable[_NT_SIZE] = { &TRAVerror, &DELids, &DELarrexpr, &DELfundefs, &DELstefun, &DELstevar, &DELbool, &DELfloat, &DELnum, &DELvar, &DELexprs, &DELfuncall, &DELcast, &DELvarlet, &DELternaryop, &DELmonop, &DELbinop, &DELreturn, &DELfor, &DELdowhile, &DELwhile, &DELifelse, &DELexprstmt, &DELassign, &DELstmts, &DELvardecl, &DELparam, &DELfunbody, &DELfundef, &DELglobdef, &DELglobdecl, &DELdecls, &DELprogram, };
const ccn_trav_ft ccn_error_vtable[_NT_SIZE] = { &TRAVerror, &TRAVerror,&TRAVerror,&TRAVerror,&TRAVerror,&TRAVerror,&TRAVerror,&TRAVerror,&TRAVerror,&TRAVerror,&TRAVerror,&TRAVerror,&TRAVerror,&TRAVerror,&TRAVerror,&TRAVerror,&TRAVerror,&TRAVerror,&TRAVerror,&TRAVerror,&TRAVerror,&TRAVerror,&TRAVerror,&TRAVerror,&TRAVerror,&TRAVerror,&TRAVerror,&TRAVerror,&TRAVerror,&TRAVerror,&TRAVerror,&TRAVerror,&TRAVerror,};
const ccn_trav_ft *ccn_trav_vtable[_TRAV_SIZE] = { ccn_error_vtable, assemblycodegeneration_vtable, compilingbooleancastexpressions_vtable, compilingbooleandisjunctionandconjunction_vtable, annotateuselesscastexpressions_vtable, typematchingassignmentsfuncalls_vtable, convertfortowhile_vtable, regularassignments_vtable, linkfuncallstostefunnode_vtable, createfunctionsymboltableentries_vtable, createvariablesymboltableentries_vtable, renameforidentifiers_vtable, print_vtable, ccn_free_vtable, ccn_check_vtable, ccn_copy_vtable, };
const ccn_trav_data_ft trav_data_init_vtable[_TRAV_SIZE] = {TRAVdataNOP,TRAVdataInitAssemblyCodeGeneration,TRAVdataNOP,TRAVdataNOP,TRAVdataNOP,TRAVdataInitTypeMatchingAssignmentsFunCalls,TRAVdataNOP,TRAVdataNOP,TRAVdataNOP,TRAVdataNOP,TRAVdataNOP,TRAVdataInitRenameForIdentifiers,TRAVdataNOP,TRAVdataNOP, TRAVdataNOP, TRAVdataNOP};
const ccn_trav_data_ft trav_data_free_vtable[_TRAV_SIZE] = {TRAVdataNOP,TRAVdataFreeAssemblyCodeGeneration,TRAVdataNOP,TRAVdataNOP,TRAVdataNOP,TRAVdataFreeTypeMatchingAssignmentsFunCalls,TRAVdataNOP,TRAVdataNOP,TRAVdataNOP,TRAVdataNOP,TRAVdataNOP,TRAVdataFreeRenameForIdentifiers,TRAVdataNOP,TRAVdataNOP, TRAVdataNOP, TRAVdataNOP};
